### ISSUE TITLE
Errors when trying to export code

### ISSUE THREAD

**Issue by EgguProgramming** [harpwood/AseFlixel#1]
I am trying to export some code for my sprites, but, it returns the errors you see in the image below.

![image](https://github.com/harpwood/AseFlixel/assets/100107293/797b149a-13f5-44fb-a37c-638062e9604e)

first time using a script like this, so I may have done something incorrectly. I have a tag set for the animation, and the animation is 3 frames long with 1 layer.

**Comment by harpwood** [comment]
Can you tell me which version of Aseprite you have? You either have a version prior the 1.3 beta or there something wrong with the data you included in the 'user data' field: 
![image](https://github.com/harpwood/AseFlixel/assets/44503874/03c72161-6a54-4ced-854b-cee69c127008)

PS. I should update the prerequisites that Aseprite 1.3 beta or newer is required.

**Comment by EgguProgramming** [comment]
ah, seems to be why. I am running 1.2.40, on steam.

![image](https://github.com/harpwood/AseFlixel/assets/100107293/94fa11fd-e385-44d7-8b1e-8a5dc9d70ef9)

**Comment by EgguProgramming** [comment]
yep - upon going to beta 1.3, it exported perfectly. thank you
